apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api-proxy
  namespace: default
  labels:
    app: github-api-proxy
    tier: resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-api-proxy
      tier: resource
  template:
    metadata:
      name: github-api-proxy
      labels:
        app: github-api-proxy
        tier: resource
    spec:
      containers:
      - name: github-api-proxy
        image: impyrio/github-api-proxy:${DOCKER_IMAGE_TAG}
        ports:
          - name: http
            containerPort: 8000
        env:
          - name: AUTH
            valueFrom:
              secretKeyRef:
                name: github-api-auth
                key: authorization
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: session-config
                key: mongo-uri
          - name: MONGO_DB
            valueFrom:
              secretKeyRef:
                name: session-config
                key: mongo-db
          - name: MONGO_COLLECTION
            valueFrom:
              secretKeyRef:
                name: session-config
                key: mongo-collection
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: session-config
                key: session-secret
        resources:
          requests:
            cpu: 0m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: github-api-proxy
spec:
  selector:
    app: github-api-proxy
    tier: resource
  ports:
  - name: http
    port: 8000
    targetPort: http